sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - bower_components
install: yarn install
script:
  - npm run build
  - hassio/script/build_hassio
  # Because else eslint fails because hassio has cleaned that build
  - ./node_modules/.bin/gulp gen-icons-app
  - npm run test
  # - xvfb-run wct --module-resolution=node --npm
  # - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --module-resolution=node --npm --plugin sauce; fi'
services:
  - docker
before_deploy:
  - "docker pull lokalise/lokalise-cli@sha256:2198814ebddfda56ee041a4b427521757dd57f75415ea9693696a64c550cef21"
deploy:
  provider: script
  script: script/travis_deploy
  "on":
    branch: master
dist: trusty
addons:
  sauce_connect: true
