name: Demo deployment

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - dev
      - master

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    name: Demo Development
    if: github.event_name != 'push' || github.ref_name != 'master'
    environment:
      name: Demo Development
      url: ${{ steps.deploy.outputs.NETLIFY_LIVE_URL || steps.deploy.outputs.NETLIFY_URL }}
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@v4.1.1
        with:
          ref: dev

      - name: Setup Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Demo
        run: ./node_modules/.bin/gulp build-demo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Netlify
        id: deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=demo/dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEMO_DEV_SITE_ID }}

  deploy_master:
    runs-on: ubuntu-latest
    name: Demo Production
    if: github.event_name == 'push' && github.ref_name == 'master'
    environment:
      name: Demo Production
      url: ${{ steps.deploy.outputs.NETLIFY_LIVE_URL || steps.deploy.outputs.NETLIFY_URL }}
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@v4.1.1
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Demo
        run: ./node_modules/.bin/gulp build-demo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Netlify
        id: deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=demo/dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEMO_SITE_ID }}
