name: Design preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - dev

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  preview:
    runs-on: ubuntu-latest
    # Skip running on forks since it won't have access to secrets
    # Skip running PRs without 'needs design preview' label
    if: github.repository == 'home-assistant/frontend' && contains(github.event.pull_request.labels.*.name, 'needs design preview')
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Gallery
        run: ./node_modules/.bin/gulp build-gallery
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy preview to Netlify
        id: deploy
        run: |
          npx -y netlify-cli@23.7.3 deploy --dir=gallery/dist --alias "deploy-preview-${{ github.event.number }}" \
            --json > deploy_output.json
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GALLERY_SITE_ID }}

      - name: Generate summary
        run: |
          NETLIFY_LIVE_URL=$(jq -r '.deploy_url' deploy_output.json)
          echo "$NETLIFY_LIVE_URL" >> "$GITHUB_STEP_SUMMARY"
